### ISSUE TITLE
Let's start from create some guides like roadmap or something like that.

### ISSUE THREAD

**Issue by hadihammurabi** [fcarvalhodev/vuegeta#4]

**Comment by fcarvalhodev** [comment]
Hello @hadihammurabi , how are you ?

Of course, we can do that! I'm just changed my current job this month, so I'm really busy right now! But next month I'm totally back in to this project, then we can start something, what do you think ?

**Comment by hadihammurabi** [comment]
Very happy to hear that. For now, I'm waiting for a project plan where to start and where to go.

If you need help, we can work together. Feel free to contact me.

**Comment by fcarvalhodev** [comment]
All right! Thanks!
